// <auto-generated />
using System;
using System.Collections.Generic;
using BoilerPlateNetCore10.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoilerPlateNetCore10.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260204145052_AddLogin")]
    partial class AddLogin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoilerPlateNetCore10.Domain.Entities.Enterprise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "BoilerPlateNetCore10.Domain.Entities.Enterprise.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Complement")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("Number")
                                .HasColumnType("int");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CNPJ", "BoilerPlateNetCore10.Domain.Entities.Enterprise.CNPJ#CNPJ", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("nvarchar(14)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "BoilerPlateNetCore10.Domain.Entities.Enterprise.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Phone", "BoilerPlateNetCore10.Domain.Entities.Enterprise.Phone#Phone", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar(11)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Enterprises", (string)null);
                });

            modelBuilder.Entity("BoilerPlateNetCore10.Domain.Entities.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "BoilerPlateNetCore10.Domain.Entities.Person.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Complement")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("Number")
                                .HasColumnType("int");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CPF", "BoilerPlateNetCore10.Domain.Entities.Person.CPF#CPF", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar(11)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "BoilerPlateNetCore10.Domain.Entities.Person.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Phone", "BoilerPlateNetCore10.Domain.Entities.Person.Phone#Phone", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar(11)");
                        });

                    b.HasKey("Id");

                    b.ToTable("People", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BoilerPlateNetCore10.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PermissionLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpire")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("UserSensitiveData", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserId");

                    b.ToTable("UsersSensitiveData", (string)null);
                });

            modelBuilder.Entity("BoilerPlateNetCore10.Domain.Entities.Customer", b =>
                {
                    b.HasBaseType("BoilerPlateNetCore10.Domain.Entities.Person");

                    b.Property<DateTime>("Since")
                        .HasColumnType("datetime2");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint");

                    b.HasIndex("SupplierId");

                    b.ToTable("People", (string)null);

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("BoilerPlateNetCore10.Domain.Entities.Employee", b =>
                {
                    b.HasBaseType("BoilerPlateNetCore10.Domain.Entities.Person");

                    b.Property<DateTime>("Admission")
                        .HasColumnType("datetime2");

                    b.Property<long>("EmployerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Resignation")
                        .HasColumnType("datetime2");

                    b.HasIndex("EmployerId");

                    b.ToTable("People", (string)null);

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("UserSensitiveData", b =>
                {
                    b.HasOne("BoilerPlateNetCore10.Domain.Entities.User", "User")
                        .WithOne("SensitiveData")
                        .HasForeignKey("UserSensitiveData", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BoilerPlateNetCore10.Domain.Entities.Customer", b =>
                {
                    b.HasOne("BoilerPlateNetCore10.Domain.Entities.Enterprise", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BoilerPlateNetCore10.Domain.Entities.Employee", b =>
                {
                    b.HasOne("BoilerPlateNetCore10.Domain.Entities.Enterprise", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("BoilerPlateNetCore10.Domain.Entities.User", b =>
                {
                    b.Navigation("SensitiveData");
                });
#pragma warning restore 612, 618
        }
    }
}
